import path from "node:path";
import dotenv from "dotenv";

dotenv.config({ path: path.join(process.cwd(), ".env") });

const env = (key: string, fallback = "") => process.env[key] ?? fallback;

export default {
	node_env: env("NODE_ENV"),
	port: env("PORT"),
	database_url: env("DATABASE_URL"),
	bak_url: env("BACKEND_URL", env("APP_URL")),
	backend_url: env("BACKEND_URL", env("APP_URL")),
	frontend_url: env("FRONTEND_URL"),
	bcrypt_salt_rounds: env("BCRYPT_SALT_ROUNDS"),
	jwt_access_secret: env("JWT_ACCESS_SECRET"),
	jwt_refresh_secret: env("JWT_REFRESH_SECRET"),
	jwt_access_expires_in: env("JWT_ACCESS_EXPIRES_IN"),
	jwt_refresh_expires_in: env("JWT_REFRESH_EXPIRES_IN"),
	redis_user: env("REDIS_USER"),
	redis_password: env("REDIS_PASSWORD"),
	redis_host: env("REDIS_HOST"),
	redis_port: env("REDIS_PORT"),
	cloudinary_api_key: env("CLOUDINARY_API_KEY"),
	cloudinary_api_secret: env("CLOUDINARY_API_SECRET"),
	cloudinary_cloud_name: env("CLOUDINARY_CLOUD_NAME"),
	smtp_user: env("SMTP_USER"),
	smtp_password: env("SMTP_PASSWORD"),
	email_sender: env("EMAIL_SENDER", env("SMTP_USER")),
	google_client_id: env("GOOGLE_CLIENT_ID"),
	super_admin_name: env("SUPER_ADMIN_NAME"),
	super_admin_email: env("SUPER_ADMIN_EMAIL"),
	super_admin_password: env("SUPER_ADMIN_PASSWORD"),
	admin_name: env("ADMIN_NAME"),
	admin_email: env("ADMIN_EMAIL"),
	admin_password: env("ADMIN_PASSWORD"),
	teacher_name: env("TEACHER_NAME"),
	teacher_email: env("TEACHER_EMAIL"),
	teacher_password: env("TEACHER_PASSWORD"),
	seed_department_name: env("SEED_DEPARTMENT_NAME", "Computer Science"),
	seed_department_code: env("SEED_DEPARTMENT_CODE", "CSE"),
	seed_semester_name: env("SEED_SEMESTER_NAME", "Fall"),
	seed_semester_year: env("SEED_SEMESTER_YEAR", "2026"),
	seed_course_code: env("SEED_COURSE_CODE", "CSE101"),
	seed_course_title: env("SEED_COURSE_TITLE", "Introduction to Programming"),
	seed_course_credit_hours: env("SEED_COURSE_CREDIT_HOURS", "3"),
	seed_section_code: env("SEED_SECTION_CODE", "A"),
	seed_section_capacity: env("SEED_SECTION_CAPACITY", "40"),
	seed_student_section_code: env("SEED_STUDENT_SECTION_CODE", "A"),
	bkash_base_url: env("BKASH_BASE_URL"),
	bkash_username: env("BKASH_USERNAME"),
	bkash_password: env("BKASH_PASSWORD"),
	bkash_app_key: env("BKASH_APP_KEY"),
	bkash_app_secret: env("BKASH_APP_SECRET"),
	bkash_callback_url: env("BKASH_CALLBACK_URL"),
	credit_fee_rate: Number(env("CREDIT_FEE_RATE", "2000")),
	max_credits_per_semester: Number(env("MAX_CREDITS_PER_SEMESTER", "25")),
};
