import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
	node_env: process.env.NODE_ENV,
	port: process.env.PORT,
	database_url: process.env.DATABASE_URL,
	bak_url: process.env.BACKEND_URL ?? process.env.APP_URL,
	backend_url: process.env.BACKEND_URL ?? process.env.APP_URL,
	frontend_url: process.env.FRONTEND_URL,
	bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
	jwt_access_secret: process.env.JWT_ACCESS_SECRET!,
	jwt_refresh_secret: process.env.JWT_REFRESH_SECRET!,
	jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN!,
	jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN!,
	redis_user: process.env.REDIS_USER!,
	redis_password: process.env.REDIS_PASSWORD!,
	redis_host: process.env.REDIS_HOST!,
	redis_port: process.env.REDIS_PORT!,
	cloudinary_api_key: process.env.CLOUDINARY_API_KEY!,
	cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET!,
	cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME!,
	smtp_user: process.env.SMTP_USER!,
	smtp_password: process.env.SMTP_PASSWORD!,
	email_sender: process.env.EMAIL_SENDER ?? process.env.SMTP_USER!,
	google_client_id: process.env.GOOGLE_CLIENT_ID!,
	super_admin_name: process.env.SUPER_ADMIN_NAME,
	super_admin_email: process.env.SUPER_ADMIN_EMAIL,
	super_admin_password: process.env.SUPER_ADMIN_PASSWORD,
	admin_name: process.env.ADMIN_NAME,
	admin_email: process.env.ADMIN_EMAIL,
	admin_password: process.env.ADMIN_PASSWORD,
	teacher_name: process.env.TEACHER_NAME,
	teacher_email: process.env.TEACHER_EMAIL,
	teacher_password: process.env.TEACHER_PASSWORD,
	seed_department_name: process.env.SEED_DEPARTMENT_NAME ?? "Computer Science",
	seed_department_code: process.env.SEED_DEPARTMENT_CODE ?? "CSE",
	seed_semester_name: process.env.SEED_SEMESTER_NAME ?? "Fall",
	seed_semester_year: process.env.SEED_SEMESTER_YEAR ?? "2026",
	seed_course_code: process.env.SEED_COURSE_CODE ?? "CSE101",
	seed_course_title:
		process.env.SEED_COURSE_TITLE ?? "Introduction to Programming",
	seed_course_credit_hours: process.env.SEED_COURSE_CREDIT_HOURS ?? "3",
	seed_section_code: process.env.SEED_SECTION_CODE ?? "A",
	seed_section_capacity: process.env.SEED_SECTION_CAPACITY ?? "40",
	seed_student_section_code: process.env.SEED_STUDENT_SECTION_CODE ?? "A",
	bkash_base_url: process.env.BKASH_BASE_URL!,
	bkash_username: process.env.BKASH_USERNAME!,
	bkash_password: process.env.BKASH_PASSWORD!,
	bkash_app_key: process.env.BKASH_APP_KEY!,
	bkash_app_secret: process.env.BKASH_APP_SECRET!,
	bkash_callback_url: process.env.BKASH_CALLBACK_URL!,
};
